### ISSUE TITLE
Missing "commons" package 

### ISSUE THREAD

**Issue by LukaszBlasiak** [Hitachi-Data-Systems/anywhere-fss-sdk#1]
Hello,
Thank you for Anywhere SDK but unfortunately I am facing with missing package problem. I can not manage to run your library due to NoClassDefFoundError exception for InvalidInputException. I have made inspection of the .jar file but I can not find mentioned class as well as "commons" package. I decompiled AnywhereConnector.java and I do believe there might be more missing files. Could you check whether there are some missing files or .jar package is corrupted on the gradle repository?

Java version: open-jdk 11.0.2
anywhere-fss-sdk: 4.3.2.32
anywhere-reporting-sdk: 4.3.2.32
okhttp: 4.4.1
gradle version: 5.2.1
Exception stacktrace:
```
java.lang.NoClassDefFoundError: com/hds/commons/exception/InvalidInputException
at com.hds.hcpaw.fss.api.AnywhereConnector$Builder.<init>(AnywhereConnector.java:692) ~[anywhere-fss-sdk-4.3.2.32.jar:na]
at com.hds.hcpaw.fss.api.AnywhereAPI$Builder.<init>(AnywhereAPI.java:255) ~[anywhere-fss-sdk-4.3.2.32.jar:na]
// my project methods ...
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) ~[spring-aop-5.2.1.RELEASE.jar:5.2.1.RELEASE]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.1.RELEASE.jar:5.2.1.RELEASE]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.1.RELEASE.jar:5.2.1.RELEASE]
at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.2.1.RELEASE.jar:5.2.1.RELEASE]
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.ClassNotFoundException: com.hds.commons.exception.InvalidInputException
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[na:na]
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	... 14 common frames omitted

**Comment by rachd12** [comment]
Thanks for raising this issue, the commons dependency was missing from the previous jar file. There is a 4.3.2.33 SDK version that should be available that has the required missing files.

**Comment by LukaszBlasiak** [comment]
Thank you, it solved this issue.

**Comment by LukaszBlasiak** [comment]
Thank you for a new SDK version. However I am getting a new problem with gradle. It is probably related to the 4.3.2.33 and 4.3.2.32 versions because 4.0.0.12 works fine.
Java version: open-jdk 11.0.2
anywhere-fss-sdk: 4.3.2.33
okhttp: 4.6.0
gradle version: 5.2.1
```Execution failed for task ':bootWar'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find com.hds:hds-commons:1.0.112.
     Required by:
         project : > com.hds.hcpaw:anywhere-fss-sdk:4.3.2.33

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by LukaszBlasiak** [comment]
In addition, I am getting incompatibility exception. Is it possible or workaround to run your SDK with Java version 9+? Should I open a new issue for this one?
```
java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+
	at okhttp3.internal.platform.Jdk9Platform.trustManager(Jdk9Platform.kt:61)
	at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:751)
	at com.hds.hcpaw.fss.api.AnywhereConnector$Builder.getClient(AnywhereConnector.java:894)
	at com.hds.hcpaw.fss.api.AnywhereConnector$Builder.build(AnywhereConnector.java:701)
	at com.hds.hcpaw.fss.api.AnywhereAPI$Builder.build(AnywhereAPI.java:264)
	--- my method
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by JeffHensel** [comment]
Hi LukaszBlasiak,

Chiming in with the newest sdk drop I have confirmed I was able to make a basic program with the sdktest class and avoid those compile time issues.

That being said at first I too ran into that issue the reason is if you accidentally downloaded the wrong jar (ie source or other) it does not include the compiled release classes for the commons library which we use internally. One way to check this would be to extract or look into the jar and ensure the commons directory is in it.

The external jars I needed to include were:
gson 2.8
guava 18.0
okhttp 3.11.0
okio 1.14.0
commons-codex 1.10 (apache for the hex library)
openjdk 1.8.0
anywhere-fss-sdk 4.3.2.33

If you still run into the issue after re-downloading the jar let me know and I'd be happy to post the bare bones project.

Cheers,
Jeffrey Hensel
Development Engineer Hitachi Vantara

**Comment by LukaszBlasiak** [comment]
Hi Jeffrey Hensel,

Thank you for your time and reply. 
Version 4.3.2.33 solved missing package problem and it contains commons directory indeed. I am sorry for misunderstanding, I should mention it in previous answer.

However I am facing with the other dependency problem. 4.3.2.33 and 4.3.2.32 versions have following entry in .pom file:
```
<dependency>
      <groupId>com.hds</groupId>
      <artifactId>hds-commons</artifactId>
      <version>1.0.112</version>
      <scope>runtime</scope>
</dependency>
```
And I believe it causes following gradle error:
```
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find com.hds:hds-commons:1.0.112.
     Required by:
         project : > com.hds.hcpaw:anywhere-fss-sdk:4.3.2.32

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```
Gradle is trying to download missing dependency but it can not be found in official maven repository. Maybe your local machine contains previously compiled "hds-commons:1.0.112" package or your project is pointing to some additional repository? You have mentioned that you are using commons library internally - maybe that internal-only access causes the problem?
From my side, I tried build my project with the same dependencies as your but unfortunately with no success.

Greetings,
Lukasz Blasiak

**Comment by JeffHensel** [comment]
You need to swap it to "compile" for scope I believe.

Let me know if that corrects the issue.
Thanks,
Jeffrey Hensel

**Comment by LukaszBlasiak** [comment]
I swapped to "compile" in _anywhere-fss-sdk-4.3.2.33.pom_ file, under gradle repository folder, but unfortunately it doesn't solve the issue.

Cheers,
Lukasz Blasiak

**Comment by JeffHensel** [comment]
Oh hmm actually you can remove that dependency all together I believe.... As long as you include the fss sdk library:
`<dependency>
  <groupId>com.hds.hcpaw</groupId>
  <artifactId>anywhere-fss-sdk</artifactId>
  <version>4.3.2.33</version>
</dependency>`

Hopefully that fixes it

**Comment by LukaszBlasiak** [comment]
I believe that is not the best approach to solve this kind of issue because every developer in our team have to keep on mind to manually edit local files under gradle directory. 
Anyway thanks for your time.

Cheers,
Lukasz Blasiak

**Comment by JeffHensel** [comment]
We will be updating the pom file with the correct dependencies.

Thank you much for your time in helping us figure out what was going wrong,
Jeffrey Hensel
